dist: trusty
language: node_js
node_js:
- stable
notifications:
    email:
        recipients:
        - skouri@yahoo.com      # change to your own address
        on_success: never        # default: change
        on_failure: always       # default: always
script:
- npm run build
deploy:
   provider: surge
   skip_cleanup: true
   domain: your-domain.surge.sh
   project: ./build/
   on:
       branch: master